- name: First Demo Pull
  hosts: local
  tasks:
      - name: print hello world
        debug:
            msg: "Hello world"
      - name: print hosts name
        debug:
            var: ansible_hostname
      - name: print Ubuntu version
        debug:
            var: ansible_distribution
